spring.application.name=backend

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

server.port=${PORT:4000}

# CORS
app.cors.allowed-origin=${FRONTEND_URL:http://localhost:4200}
